version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    hostname: jaeger
    container_name: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
      - 14250:14250
    networks:
      - tracingdemo
  collector:
    image: otel/opentelemetry-collector:latest
    container_name: collector
    hostname: collector
    command: ["--config=/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/otel-collector-config.yml
    ports:
      - 4317:4317
    depends_on:
      - jaeger
    networks:
      - tracingdemo

networks:
  tracingdemo:
