-- create stream from topic
CREATE STREAM S_INPUT (URL STRING) WITH (KAFKA_TOPIC='async-queue-enriched', KEY_FORMAT='KAFKA', VALUE_FORMAT='JSON');

-- convert data type to avro
CREATE STREAM S_AVRO WITH (KAFKA_TOPIC='S_AVRO', KEY_FORMAT='avro', PARTITIONS=1, REPLICAS=1, VALUE_FORMAT='avro') AS SELECT *
FROM S_INPUT S_INPUT
EMIT CHANGES;

-- windowing count
CREATE TABLE T_PV_COUNT WITH (KAFKA_TOPIC='T_PV_COUNT', PARTITIONS=1, REPLICAS=1) AS SELECT
  -- ROWKEY is defined in AVRO key, does not exist in AVRO value.
  S_AVRO.URL ROWKEY,
  -- To add a URL to AVRO value, need to use AS_VALUE() function.
  AS_VALUE(S_AVRO.URL) URL,
  AS_VALUE(WINDOWSTART) ST,
  AS_VALUE(WINDOWEND) ED,
  COUNT(*) COUNT
FROM S_AVRO S_AVRO
WINDOW TUMBLING ( SIZE 10 SECONDS )
GROUP BY S_AVRO.URL
EMIT CHANGES;
